### ISSUE TITLE
How is the privateKey.txt generated in Exercise 24 ?

### ISSUE THREAD

**Issue by boudhayan-dev** [SAP/cloud-bulletinboard-ads#15]
Hi,

I understand that the publicKey.txt is obtained from the VCAP_SER VICES. But I could not find the private key under it. How was that generated ?

**Comment by nenaraab** [comment]
Dear Boudhayan,

for testing purposes it is explained [here](https://github.com/SAP/cloud-bulletinboard-ads/blob/Documentation/Security/Exercise_24_MakeYourApplicationSecure.md). 

In productive environments the XSUAA service signs the token with a private key.

Thanks and best regards,
Nena

**Comment by boudhayan-dev** [comment]
Hi @nenaraab ,

I have taken a look but I could not find details about the **generation of the Private Key**. In the Readme -

> Create folder cc-bulletinboard-ads/src/test/resources and copy the files privateKey.txt, publicKey.txt into the new folder.

Here, it just says copy the private key from the `privateKey.txt` file . I want to know, how is that private Key generated ? For the public key, I can check the `VCAP_SERVICES ` of the deployed app and find it. Is there a way to find the Private Key as well ?

**Comment by nenaraab** [comment]
Hi @boudhayan-dev 
this is easy to explain. We have generated a private/public key pair 
- privateKey for signing the JWT token and 
- publicKey for the locally used VCAP_SERVICES 
This is only a fake for JUnit tests and for testing the application locally without having a xsuaa service connected to... as explained [here](https://github.com/SAP/cloud-bulletinboard-ads/blob/Documentation/Security/Exercise_24_MakeYourApplicationSecure.md).

hope that answers your question?

**Comment by boudhayan-dev** [comment]
Hi @nenaraab ,

Thanks , that explains. I could generate my own Key-Value pair and use it for local testing.
