### ISSUE TITLE
How to enable SSO ?

### ISSUE THREAD

**Issue by boudhayan-dev** [SAP/cloud-bulletinboard-ads#16]
Hi,

With respect to Exercise 24, Instead of prompting for Username and Password from the user every time, is there a way to take the credentials from the host machine once the user has logged in ? For SAP employees, it makes sense to automatically log in the user without prompting the login page.

**Comment by nenaraab** [comment]
Hi Boudhayan,

please have a look into this documentation:
https://help.sap.com/viewer/462e41a242984577acc28eae130855ad/Cloud/en-US/6080a929b4bc4ad482a8998ed6a92a2f.html

Best regards
