### ISSUE TITLE
VirtutalBox is black listed

### ISSUE THREAD

**Issue by ikushn** [SAP/cloud-bulletinboard-ads#17]
Hi @svenkohlhaas ,

The VirtutalBox is now black listed at SAP.

Can we update the image to use another VM tool?

Thanks,
Ilia

**Comment by svenkohlhaas** [comment]
Hi Ilia,

internally, please use the VM of the internal classroom version of the course which is VMware-based. I've sent you the link via e-mail.

All the best,
Sven

P.S. Please don't post internal links in the public GitHub.
