### ISSUE TITLE
Error pom.xml

### ISSUE THREAD

**Issue by Elrut** [SAP/cloud-bulletinboard-ads#2]
Hello, I had the following error, how to fix?
`Cannot read lifecycle mapping metadata for artifact org.apache.maven.plugins:maven-compiler-plugin:maven-plugin:3.3:runtime Cause: invalid END header (bad central directory offset)`
https://pp.userapi.com/c846120/v846120720/dfee/V_JI0EuR8Rg.jpg

**Comment by skrishnakumar** [comment]
Hello,

Can you please share more details? which branch are you working with and what was the command that you ran? the screen shot that you have attached is not accessible

**Comment by Vest** [comment]
I don't have this issue, but I used **_mvn_** instead of Eclipse. Probably the solution is described [here](https://stackoverflow.com/questions/43366254/invalid-end-header-bad-central-directory-size-zipexception).

**Comment by nenaraab** [comment]
Please find here further information on how to run the application within Eclipse IDE or on command line (terminal):
https://github.com/SAP/cloud-bulletinboard-ads/blob/Documentation/CreateMicroservice/Exercise_1_GettingStarted.md

and what to do, when you face issues with `pom.xml`:
https://github.com/SAP/cloud-bulletinboard-ads/blob/Documentation/Knowledge/TroubleShooting.md#issues-with-pomxml-or-error-updating-maven-configurations

Good luck!
