### ISSUE TITLE
Publishing to Tomcat v8.5 Server at localhost.. error 

### ISSUE THREAD

**Issue by kanmach** [SAP/cloud-bulletinboard-ads#3]
Noticed couple of errors while trying to "update project from Maven" and trying to "start the server"

"Publishing to Tomcat v8.5 Server at localhost... has encountered a problem.
Could not publish to the server.
java.lang.IndexOutOfBoundsException"

![err1](https://user-images.githubusercontent.com/38475705/38898278-0c3555ea-4284-11e8-8774-6666765cc4b1.JPG)

![err2](https://user-images.githubusercontent.com/38475705/38898285-13e5f3bc-4284-11e8-8834-8065edf08f4c.JPG)

**Comment by skrishnakumar** [comment]
This could be due to a corrupt repository. Hence some solutions are provided in this stackoverflow  discussion https://stackoverflow.com/questions/20145399/eclipse-tomcat-7-java-lang-indexoutofboundsexception-on-publish?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
