### ISSUE TITLE
Documentation improvement (exercise 3 all ads endpoint)

### ISSUE THREAD

**Issue by mhnagaoka** [SAP/cloud-bulletinboard-ads#4]
On the [week 2, unit 2 video](https://open.sap.com/courses/cp5/items/1MXAA0KGDp9jkMuFUiKQO4), around 9:20, it's possible to see that the `advertisements()` method returns a `AdvertisementList` instead of `Iterable<Advertisement>` as stated on [Exercise 3, Step 1](https://github.com/mhnagaoka/cloud-bulletinboard-ads/blob/556a7519b6ffa6a0a1465cdc56816431c6913bca/CreateMicroservice/Exercise_3_CreateAdsEndpoints.md#step-1-create-advertisement-service).

Perhaps we could fix the base `AdvertisementController` implementation given on the exercise to include this class.

**Comment by nenaraab** [comment]
please see here (my comments to your pull request):
https://github.com/SAP/cloud-bulletinboard-ads/pull/5
