### ISSUE TITLE
use endpoints with <<region>> endpoints

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-bulletinboard-ads#7]
Search for `sap.hana.ondemand` and replace this with `<<region>>.hana.ondemand` and add the following note:

The `<<region>>` needs to be replaced with eu10 or us10 depending on the trial environment where you have registered.

These Exercises are affected, e.g.:
- Exercise 16, 24 Part 2

**Comment by svenkohlhaas** [comment]
In Exercise 16 it's always already eu10.hana.ondemand.com, but there probably doing `<<region>>`.hana.ondemand.com and a statement to replace the `<<region>>` with eu10 or us10 would be beneficial as well.

**Comment by skrishnakumar** [comment]
This has been updated in exercise 16, 24 part 2
