### ISSUE TITLE
Exercise 16 / Step 5 - missing open Todo

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-bulletinboard-ads#8]
See also cp5 discussion:
https://open.sap.com/courses/cp5/question/66e9a1c1-fa73-45c5-9e91-daf123da75fb

There was a missing openTodo...

I've tried to fix it, please review and follow up here!

**Comment by skrishnakumar** [comment]
fixed to-do with commit eb7e49d

**Comment by nenaraab** [comment]
@skrishnakumar 
Please double check on my [commit](https://github.com/SAP/cloud-bulletinboard-ads/commit/ecf8c71252cb9c62f9632df85222a0b65b82c53f), please :-)

**Comment by skrishnakumar** [comment]
@nenaraab i have checked the region and changed from eu10 to region.
I have also added the comment at the beginning that region needs to be replaced. So, not sure what you want me to double check?

**Comment by nenaraab** [comment]
Dear Krishna, 
The commit, I've linked:
https://github.com/SAP/cloud-bulletinboard-ads/commit/ecf8c71252cb9c62f9632df85222a0b65b82c53f
:-)
